### ISSUE TITLE
Inaccurate/confusing example?

### ISSUE THREAD

**Issue by SEAPUNK** [zeit/async-retry#15]
In example,

``` js
// ...
return await retry(async (bail) => {
  // ...
  if (403 === res.status) {
    // don't retry upon 403
    bail(new Error('Unauthorized'));
  }
  // ...
}
// ...
```

Shouldn't that be `return bail`? Otherwise, it passes through, and attempts to also return the text substring, which wastes resources.

**Comment by SEAPUNK** [comment]
On a side note, I wrote my own retry library yesterday for fun and profit, and also because I felt that using the old `node-retry` library was fairly limiting and inadequate...

I didn't make a PR here because it has a few huge breaking changes, and I wasn't sure if you'd like those changes to go into this project: https://github.com/SEAPUNK/recaller

**Comment by leo** [comment]
e98277dac7980ecf1128c68c29271ff96f50808a
