### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jgoux** [zeit/async-retry#31]
Hello,

I have these warnings when the retry is trigerred : 
```
(node:27189) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 44): TypeError: Cannot read property 'onRetry' of undefined
```

This is how I use `retry` : 
```javascript
const _retryGeocode = (address) => (
  retry((bail) => (
    _geocode(address).catch(e =>
      e === 'OVER_QUERY_LIMIT'
        ? Promise.reject(e)
        : bail(e)
    )
  ))
)
```
I'm on node v6.9.1

As I don't provide any option to the retry function, I don't understand why these warnings occur as [the `opt` is initialized as an empty object by default](https://github.com/zeit/async-retry/blob/master/lib/index.js#L4).

**Comment by OlliV** [comment]
I was hit by the same issue, it works if you give it an empty opt object.

**Comment by TooTallNate** [comment]
I don't believe this should be possible from reading the code. Going to close this one for now.

Post with some repro code if you feel this is still an issue.
