### ISSUE TITLE
bail on certain errors?

### ISSUE THREAD

**Issue by brandonmp** [zeit/async-retry#33]
is there a way to check a thrown `error` before deciding to retry? I tried wrapping my `await` line in a `try/catch` & `bail()`/`throw` depending on `error.message`, but that's making my unit tests go nuts for reasons that aren't clear to me

**Comment by leo** [comment]
Take a look at the "onRetry" [property](https://github.com/zeit/async-retry#api). It's run after the retry, but you can use it to cancel the process.

**Comment by gomorizsolt** [comment]
@leo Even though this question is of old, but how can one use `onRetry()` to bail on certain failures?
